src/Entity/Trick.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TrickRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Trick
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="trick", orphanRemoval=true, cascade={"persist", "remove"})
     */
    private $images;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Video", mappedBy="trick", orphanRemoval=true, cascade={"persist", "remove"})
     */
    private $videos;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="trick", cascade={"persist", "remove"})
     */
    private $comments;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\TrickGroup", inversedBy="tricks", cascade={"persist"})
     */
    private $trick_group;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="tricks", cascade={"persist"})
     */
    private $createdBy;


    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->videos = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setTrick($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getTrick() === $this) {
                $image->setTrick(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Video[]
     */
    public function getVideos(): Collection
    {
        return $this->videos;
    }

    public function addVideo(Video $video): self
    {
        if (!$this->videos->contains($video)) {
            $this->videos[] = $video;
            $video->setTrick($this);
        }

        return $this;
    }

    public function removeVideo(Video $video): self
    {
        if ($this->videos->contains($video)) {
            $this->videos->removeElement($video);
            // set the owning side to null (unless already changed)
            if ($video->getTrick() === $this) {
                $video->setTrick(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setTrick($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getTrick() === $this) {
                $comment->setTrick(null);
            }
        }

        return $this;
    }

    public function getTrickGroup(): ?TrickGroup
    {
        return $this->trick_group;
    }

    public function setTrickGroup(?TrickGroup $trick_group): self
    {
        $this->trick_group = $trick_group;

        return $this;
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function initializeSlug()
    {
        if(empty($this->slug)){
            $slugify = new Slugify(); // Don't forget to import class
            $this->slug= $slugify->slugify($this->title);
        }

    }
    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getCreatedAt(): ?DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getCreatedBy(): ?User
    {
        return $this->createdBy;
    }

    public function setCreatedBy(?User $createdBy): self
    {
        $this->createdBy = $createdBy;

        return $this;
    }

}

src/Form/TrickType.php
<?php

namespace App\Form;

use App\Entity\Trick;
use App\Entity\TrickGroup;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class TrickType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('trick_group', EntityType::class, [
                'class' => TrickGroup::class,
                'choice_label' => 'title',
            ])
            ->add('images', CollectionType::class, [
                'entry_type'   => ImageType::class,
                'allow_add'    => true,
                'allow_delete' => true
            ])
            ->add('videos', CollectionType::class, [
                'entry_type' => VideoType::class,
                'required' => false,
                'allow_add'    => true,
                'allow_delete' => true,
                'label' => false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Trick::class,
        ]);
    }
}

src/Controller/TrickController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Trick;
use App\Form\CommentType;
use App\Form\TrickType;
use App\Repository\CommentRepository;
use DateTime;
use Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/trick")
 */
class TrickController extends AbstractController
{
    /**
     * @Route("/new", name="trick_new", methods={"GET","POST"})
     * @param Request $request
     * @return Response
     * @throws Exception
     */
    public function new(Request $request): Response
    {
        $trick = new Trick();
        $form = $this->createForm(TrickType::class, $trick);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $imagesCollection = $form->getData()->getImages();
            $videosCollection = $form->getData()->getVideos();
            foreach ($imagesCollection as $image)
            {
                $image->setTrick($trick);
                $image->setCreatedAt(new DateTime('now'));
                $trick->addImage($image);
            }
            foreach ($videosCollection as $video)
            {
                $video->setTrick($trick);
                $video->setCreatedAt(new DateTime('now'));
                $trick->addVideo($video);
            }
            $trick->setCreatedAt(new DateTime('now'));
            $trick->setCreatedBy($this->getUser());
            $entityManager = $this->getDoctrine()->getManager();

            $entityManager->persist($trick);
            $entityManager->flush();
            return $this->redirectToRoute('home');
        }

        return $this->render('trick/new.html.twig', [
            'trick' => $trick,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{slug}", name="trick_show", methods={"GET","POST"})
     * @param Request $request
     * @param Trick $trick
     * @param CommentRepository $commentRepository
     * @return Response
     * @throws Exception
     */
    public function show(Request $request, Trick $trick, CommentRepository $commentRepository): Response
    {
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $comment->setUser($this->getUser());
            $comment->setTrick($trick);
            $comment->setCreatedAt(new DateTime('now'));
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($comment);
            $entityManager->flush();

            return $this->redirectToRoute('trick_show', ['slug' => $trick->getSlug()]);
        }
        $commentToShow = 3;
        if ($request->isXmlHttpRequest()) {
            $row = $request->query->get('row');
            return new JsonResponse([
                'view'    => $this->renderView('comment/more.html.twig', [ 'comments' => $commentRepository->findBy(['trick' => $trick], null, 3, $row),])
            ]);
        }
        return $this->render('trick/show.html.twig', [
            'trick' => $trick,
            'commentToShow' => $commentToShow,
            'comments' => $commentRepository->findBy(['trick' => $trick], ['createdAt' => 'DESC'], 3, 0),
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/edit/{slug}", name="trick_edit", methods={"GET","POST"})
     * @param Request $request
     * @param Trick $trick
     * @return Response
     * @throws Exception
     */
    public function edit(Request $request, Trick $trick): Response
    {
        $form = $this->createForm(TrickType::class, $trick);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $imagesCollection = $form->getData()->getImages();
            $videosCollection = $form->getData()->getVideos();
            foreach ($imagesCollection as $image)
            {
                $image->setTrick($trick);
                $image->setUpdatedAt(new DateTime('now'));
                $trick->addImage($image);
            }
            foreach ($videosCollection as $video)
            {
                $video->setTrick($trick);
                $video->setUpdatedAt(new DateTime('now'));
                $trick->addVideo($video);
            }
            $trick->setCreatedBy($this->getUser());
            $trick->setUpdatedAt(new DateTime('now'));
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('home');
        }
        return $this->render('trick/edit.html.twig', [
            'trick' => $trick,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="trick_delete", methods={"DELETE"})
     * @param Request $request
     * @param Trick $trick
     * @return Response
     */
    public function delete(Request $request, Trick $trick): Response
    {
        if ($this->isCsrfTokenValid('delete'.$trick->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($trick);
            $entityManager->flush();
        }

        return $this->redirectToRoute('home');
    }
}

templates/trick/_delete_form.html.twig
<form method="post" action="{{ path('trick_delete', {'id': trick.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ trick.id) }}">
    <button class="btn btn-danger btn-sm" title="Delete"><i class="fa fa-trash"></i></button>
</form>

templates/trick/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Trick{% endblock %}

{% block body %}
    <div class="container-for-admin">
        <!--Main layout-->
        <div class="container-for-admin">
            <!--Main layout-->
            <main class="pt-5">
                <div class="container-fluid mt-5" style="max-width: 1440px; margin: 0 auto">
                    <a href="{{ path('home') }}" class="btn btn-outline-info btn-rounded my-4 waves-effect ">
                        Retour
                    </a>
                    <div class="position-relative">
                        <h1>Edit Trick</h1>
                    </div>
                    <div class="card-body px-lg-5 pt-0">
                        {{ form_start(form, {'attr': {'id': 'form'}}) }}
                        <div class="form-row">
                            <div class="col">
                                <!-- First name -->
                                <div class="md-form">
                                    {{ form_widget(form.title, { 'attr': {'class': 'form-control'} }) }}
                                    <label for="register_pseudo">Titre</label>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col">
                                <!-- First name -->
                                <div class="md-form">
                                    {{ form_widget(form.description, { 'attr': {'class': 'form-control'} }) }}
                                    <label for="register_pseudo">Description</label>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col">
                                <div class="md-form">
                                    {{ form_widget(form.trick_group, { 'attr': {'class': 'form-control'} }) }}
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-6 form-image">
                                {{ form_label(form.images, 'Images', {'label_attr': {'style': 'font-weight: bold'}}) }}
                                {% for image in form.images %}
                                    <div class="previous-img-{{ loop.index -1 }}">
                                        <img src="{{ asset('uploads/' ~ image.vars.data.completeUrl) }}" alt="Image" width="300">
                                        {{ form_errors(image) }}
                                        {{ form_widget(image, { 'attr': {'class': 'image-edit'} }) }}
                                    </div>
                                {% endfor %}
                                <a href="javascript:void(0)" id="add_image" class="btn btn-default">Ajouter une image</a>
                            </div>
                            <div class="col-lg-6">
                                {{ form_errors(form.videos) }}
                                {{ form_label(form.videos, 'Videos', { 'attr': {'class': 'form-control'} }) }}
                                {{ form_widget(form.videos) }}
                                <a href="javascript:void(0)" id="add_video" class="btn btn-default">Ajouter une video</a>
                            </div>
                        </div>
                        <button class="btn">{{ button_label|default('Mettre à jour') }}</button>
                        {{ form_end(form) }}
                    </div>
                </div>
            </main>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('js/nested-form-image-edit') }}
    {{ encore_entry_script_tags('js/nested-form-video-add') }}
{% endblock %}

templates/trick/more.html.twig
{% for trick in tricks %}
    <!--Grid column-->
    <article class="col-lg-3 col-md-12 mb-4">
        <!--Card-->
        <div class="card">
            <!--Card image-->
            <div class="view overlay">
                {% if trick.images %}
                    <img src="{{ asset('uploads/'~ trick.images[0].completeUrl) }}" alt="Image de présentation" class="card-img-top">
                {% else %}
                    <img src="http://placehold.it/300x200" class="card-img-top" alt="placehold.it">
                {% endif %}
                <a href="{{ path('trick_show', {'slug': trick.slug}) }}">
                    <div class="mask rgba-white-slight"></div>
                </a>
            </div>
            <!--Card content-->
            <div class="card-body">
                <!--Title-->
                <h4 class="card-title">{{ trick.title }}</h4>
                <!--Text-->
                <a href="{{ path('trick_show', {'slug': trick.slug}) }}" class="btn btn-indigo btn-sm">Voir la figure</a>

                {% if app.user %}
                    {% if app.user is same as(trick.createdBy) or app.user.roles[0] is same as('ROLE_ADMIN')%}
                        <div class="d-flex justify-content-end">
                            <a href="{{ path('trick_edit', {'slug': trick.slug}) }}" class="btn btn-info btn-sm"><i class="fa fa-pen"></i></a>
                            {{ include('trick/_delete_form.html.twig') }}
                        </div>
                    {% endif %}
                {% endif %}

            </div>
        </div>
        <!--/.Card-->
    </article>
    <!--Grid column-->

{% endfor %}

templates/trick/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello TricksController!{% endblock %}

{% block body %}
    <!--Carousel Wrapper-->
    <section style="max-width: 1440px; margin: 50px auto; padding: 0 15px">
        <h2 class="text-center p-5 d-none d-sm-block">{{ trick.title | title }}</h2>
        <article class="row">
            <aside class="col-lg-8 d-none d-sm-block">
                <!--Carousel Wrapper-->
                <div id="carousel-thumb" class="carousel slide carousel-fade carousel-thumbnails" data-ride="carousel" style="height: unset;">
                    <!--Slides-->
                    <div class="carousel-inner" role="listbox">
                        {% for image in trick.images %}
                            <div class="carousel-item {% if loop.index is same as(1) %} active {% endif %}">
                                <img class="d-block w-100"
                                     src="{{ asset('uploads/' ~ image.completeUrl) }}"
                                     alt="slide{{ loop.index }}">
                            </div>
                        {% endfor %}
                        {% for video in trick.videos %}
                            <div class="carousel-item">
                                <iframe width="800"
                                        height="500"
                                        src="https://www.youtube.com/embed/{{ video.src }}"
                                        frameborder="0"
                                        allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                                        allowfullscreen></iframe>
                            </div>
                        {% endfor %}
                    </div>
                    <!--/.Slides-->
                    <!--Controls-->
                    <a class="carousel-control-prev" href="#carousel-thumb" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carousel-thumb" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>

                </div>
                <!--/.Carousel Wrapper-->
                <!--/.Controls-->
                <ol class="d-flex justify-content-center list-inline single-trick-indicator p-3 ">
                    {% for image in trick.images %}
                        <li data-target="#carousel-thumb" data-slide-to="{{ loop.index -1 }}" class="active ">
                            <img src="{{ asset('uploads/' ~ image.completeUrl) }}" width="200" alt="Indicator{{ loop.index }}">
                        </li>
                    {% endfor %}
                    {% for video in trick.videos %}
                        <li data-target="#carousel-thumb" data-slide-to="{{ (loop.index -1) + trick.images | length }}" class="active ">
                            <img src="https://img.youtube.com/vi/{{ video.src }}/default.jpg" width="200" alt="Indicator video {{ video.title }}">
                        </li>
                    {% endfor %}
                </ol>
                <div class="text-center w-100 pb-3 d-block d-sm-none">
                    <button class="btn text-center">Voir les medias</button>
                </div>
            </aside>
            <aside class="col-lg-12 d-block d-sm-none">
                <div class="d-block d-sm-none mt-3" style="position: relative; background: url('{{ asset('uploads/' ~ trick.images[0].completeUrl) }}')center top/cover; height: 220px;">
                    <h2 class="text-center w-100 text-white" style="position: absolute; top: 30%; transform: translateY(30%);">{{ trick.title | title }}</h2>
                </div>
                <ul id="media" class="p-0 d-none">
                    {% for image in trick.images %}
                        <li class="list-group">
                            <img class="d-block w-100" src="{{ asset('uploads/' ~ image.completeUrl) }}" alt="slide{{ loop.index }}">
                        </li>
                    {% endfor %}
                    {% for video in trick.videos %}
                        <li class="list-group">
                            <iframe width="400"
                                    height="400"
                                    src="https://www.youtube.com/embed/{{ video.src }}"
                                    frameborder="0"
                                    allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                                    allowfullscreen></iframe>
                        </li>
                    {% endfor %}
                </ul>
                <div class="text-center w-100">
                    <button id="seeMediaBtn" class="btn">Voir les medias</button>
                    <button id="hideMediaBtn" class="btn d-none">Cacher les medias</button>
                </div>
            </aside>
            <div class="col-lg-4">
                <h2 class="text-center">Description</h2>
                <div class="description text-justify">{{ trick.description }}</div>
            </div>
            <div class="w-100">
                <em>Par: <strong>{{ trick.createdBy.firstname }} {{ trick.createdBy.lastname }}</strong> le {{ trick.createdBy.createdAt | date('d/m/Y') }}</em>
                <br>
                <em>Groupe: {{ trick.trickGroup.title }}</em>
                <br>
                {% if trick.updatedAt %}
                    <em>Dernière mise à jour: {{ trick.updatedAt | date('d/m/Y') }}</em>
                {% endif %}
            </div>
        </article>
        <hr class="mt-5">
        <article>
            <h2>Commentaires</h2>
            {% if app.user %}
                {{ include('comment/_form.html.twig', {'button_label': 'Ajouter'}) }}
            {% endif %}
            <div class="panel-body">
                <ul id="more" class="list-group">
                    {% for comment in comments %}
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-xs-2 col-md-1">
                                    <img class="img-circle img-responsive"
                                         src="https://eu.ui-avatars.com/api/?name={{comment.user.firstname}}+{{comment.user.lastname}}&background=0D8ABC&color=fff"
                                         alt="Initial de l'utilisateur"
                                         width="50">
                                </div>
                                <div class="col-xs-10 col-md-11">
                                    <div>
                                        <div class="mic-info">
                                            By: <a href="javascript:void(0)">{{comment.user.firstname | title }} {{comment.user.lastname | title }}</a> le  {{ comment.createdAt | date('d/m/Y') }}
                                            {% if comment.user.roles[0] is same as('ROLE_ADMIN') %}
                                                <span class="badge badge-primary">Administrateur</span>
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="comment-text">
                                        {{ comment.content }}
                                    </div>
                                    {% if app.user %}
                                        <div class="action d-flex">
                                            {% if app.user is same as(comment.user) or app.user.roles[0] is same as('ROLE_ADMIN')%}
                                                {{ include('comment/_delete_form.html.twig') }}
                                            {% endif %}
                                            {{ include('comment/_signalement_form.html.twig', {'detail': 'signaled'}) }}
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
                <button class="btn btn-primary" id="loadmore">Voir plus de commentaires</button>
            </div>
        </article>
    </section>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script>
        $(document).ready(function(){
            $("#seeMediaBtn").on("click", function () {
                $("#media").removeClass( ["d-none" ] );
                $("#hideMediaBtn").removeClass( ["d-none" ] );
                $("#seeMediaBtn").addClass( ["d-none" ] );
            });
            $("#hideMediaBtn").on("click", function () {
                $("#media").addClass( ["d-none" ] );
                $("#hideMediaBtn").addClass( ["d-none" ] );
                $("#seeMediaBtn").removeClass( ["d-none" ] );
            });
        });
    </script>
    <script>
        $(document).ready(function(){
            let count = 0   ;
            $("#loadmore").on("click", function(){
                count += {{ commentToShow }};
                $.ajax({
                    url: "{{ path('trick_show', {'slug': trick.slug})}}",
                    type: 'GET',
                    data: { row : count },
                    dataType: "json",
                    success: function (data) {
                        $("#more").append(data.view);
                    },
                    error : function() {
                        alert('Un problème est survenu lors du chargement des commentaires.');
                    }
                });
            });
        });
    </script>
{% endblock %}